apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-server
  name: nginx-server
spec:
  containers:
  - name: nginx-server-container  
    image: nginx:1.19.4  
    resources :
      requests: 
        memory : "256Mi"
        cpu: "100m"  
      limits:
        memory : "256Mi"
        cpu: "100m"
