version: '3.6'
services:

 elasticsearch:
 # Utilizar la imagen de elasticsearch v7.9.3
  image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3

 # Asignar un nombre al contenedor
  container_name: elastic_HM1ex5

 # Define las siguientes variables de entorno:
 # discovery.type=single-node
  environment:
  - discovery.type=single-node

 # Emplazar el contenedor a la red de elastic
  networks: 
  - elastic

 # Mapea el Puerto externo 9200 al puerto interno del contenedor 9200
 # Idem para el puerto 9300
  ports:
  - 9200:9200
  - 9300:9300

 kibana:
 # Utilizar la imagen kibana v7.9.3
  image: docker.elastic.co/kibana/kibana:7.9.3

 # Asignar un nombre al contenedor
  container_name: kibana_HM1ex5

 # Emplazar el contenedor a la red de elastic
  networks: 
  - elastic

 # Define las siguientes variables de entorno:
 # ELASTICSEARCH_HOST=elasticsearch
 # ELASTICSEARCH_PORT=9200
  environment:
  - ELASTICSEARCH_HOST=elasticsearch
  - ELASTICSEARCH_PORT=9200

 # Mapear el puerto externo 5601 al puerto interno 5601
  ports:
  - 5601:5601

 # El contenedor Kibana debe esperar a la disponibilidad del servicio elasticsearch
  depends_on:
  - "elasticsearch"

# Definir la red elastic (bridge)
networks:
  elastic:
    driver: bridge
